### ISSUE TITLE
using the exact same bars for multiple specs?

### ISSUE THREAD

**Issue by mkvlrn-cm42** [rscheele/KeyBindProfiles#1]
i've been using https://www.curseforge.com/wow/addons/action-bar-profiles for the longest time, but it looks like it won't be updated any time soon, and someone somewhere recommended this addon

the thing is that i may be using this one incorrectly, trying to mimic what i had going on with action-bar-profiles

when i save a profile on this one, it doesn't apply the same set of bars to the character when i swap specs

what i mean is, i aim to have *the very exact same bars on all specs*, because i just macro all my keys to work on the specs i play, things like

```lua
#showtooltip
/use [spec:1] Keg Smash
/use [spec:3] Whirling Dragon Punch
```

and this will be even more important with the new talent trees

is there anyway i can accomplish that using this addon?

**Comment by RodiScheele** [comment]
This addon only changes your keybinds, not your bars. It doesn't change your bar layout, so your bars should remain the same when you change your key bind setups.

If you want to have the same set of bars on every different specc you'll have to manually set up your bars for every single specc. Blizzard will store your bar layout for you.

**Comment by mkvlrn-cm42** [comment]
ahh, gotcha!

thanks for the reply.
